# Generated by Django 4.1.5 on 2023-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
